blank_issues_enabled: true
contact_links:
  - name: Report a security vulnerability
    url: https://github.com/DataDog/barkus/security/policy
    about: Please report security vulnerabilities through Datadog's security policy.
